insert into category (category_id, description, age_restriction)
VALUES ('PASTRY', 'Stuff that has to be baked', null),
       ('FRUIT', 'Stuff that grows mostly on trees', null),
       ('VEGETABLE', 'Stuff that grows mostly underground. It is supposed to be healthy', null),
       ('MEAT',
        'Stuff that grows on living stuff. Can be quite messy when harvesting and some people also dont like it because of moral dilemmas.',
        null),
       ('CHARCUTERIE',
        'Smoked stuff of the living things. Someone once forgot they had meat in the chimney and this happened. Coincidence? I think not!',
        null),
       ('DELICACY',
        'Stuff that only rich people buy, or comes in small sizes, or you have to be deviant enough to like it. Can be cultural or general thing.',
        null),
       ('MILK_BASED',
        'Stuff that came out of udders and then some of it happened to get bad, so yogurts came out, or cheese, or cheese with mold. All it takes it for people to forget about stuff and this happens.',
        null),
       ('FROZEN', 'Stuff that is already pre-prepared or deeply frozen so it lasts longer', null),
       ('LONG_LASTING', 'Stuff that cannot be spoiled quickly. Also contains dried stuff or stuff in tin cans.', null),
       ('ALCOHOL', 'Stuff that makes you do things you wouldnt do normally', null),
       ('BEVERAGE', 'Cold stuff, hot stuff, sprinkly stuff, also drugs like tea and coffee are included', 18);



insert into product(name, category, description)
values ('Bread', 'PASTRY', 'Round stuff that is exceptionally pricey'),
       ('Roll', 'PASTRY', 'Small round stuff that people buy with beer in order to stave hunger'),
       ('Cake', 'PASTRY', 'Not at all healthy. Sometimes leads to death or empty promises. Cake is a lie!'),
       ('Apple', 'FRUIT', 'Healthy stuff that keeps doctors away for the duration of 1 day'),
       ('Kiwi', 'FRUIT', 'Exotic overpriced stuff'),
       ('Potato', 'VEGETABLE', 'PO-TA-TOES - mash them, smash them, grill them, or distill them'),
       ('Carrot', 'VEGETABLE', 'Upgrades your vision by 10%. Although the latest study shows its not the case, you just get orange-ish'),
       ('Beef', 'MEAT', 'Steak stuff'),
       ('Pork', 'MEAT', 'Also steak stuff, but cheaper'),
       ('Sausage', 'CHARCUTERIE', 'Big wobbly thing mermaids ride on. Or wait, thats a sea.'),
       ('Salami', 'CHARCUTERIE', 'Stuff you add to pizza'),
       ('Frog legs', 'DELICACY', 'Just dont...'),
       ('Drowner', 'DELICACY', 'Tastes awful, but once you have few beers in you, it suddenly doesnt. Magic'),
       ('Yogurt', 'MILK_BASED', 'Stuff if you let milk go long enough'),
       ('Milk', 'MILK_BASED', 'What did you expect?'),
       ('Pizza', 'FROZEN', 'Round stuff with other stuff on top'),
       ('Frozen corn', 'FROZEN', 'Just corn that is frozen'),
       ('Chocolate', 'LONG_LASTING', 'Cavity creation tool. Dentists recommend 9/10 (the last one doesnt like sweets)'),
       ('Cereals', 'LONG_LASTING', 'Healthy stuff dried stuff'),
       ('Beer', 'ALCOHOL', 'Stuff that is cheaper than water'),
       ('Wine', 'ALCOHOL', 'High class stuff that makes your world spin'),
       ('Coca cola', 'BEVERAGE', 'Stuff that can make stuff disappear. It is an acid that melts rust'),
       ('Fanta', 'BEVERAGE', 'Popular drink in India');
